# Generated by Django 4.1.5 on 2023-02-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SifrantSob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SifraSobe', models.IntegerField()),
                ('TipSobe', models.CharField(max_length=10)),
                ('StOSeb', models.IntegerField()),
            ],
        ),
    ]
