# Generated by Django 4.1.5 on 2023-02-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0004_alter_vnosgostov_od'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnosgostov',
            name='od',
            field=models.CharField(max_length=100),
        ),
    ]
