# Generated by Django 4.1.5 on 2023-03-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0005_alter_vnosgostov_od'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponudba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumVnosa', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('ime', models.CharField(blank=True, max_length=30, null=True)),
                ('od', models.CharField(blank=True, max_length=30, null=True)),
                ('do', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('rna', models.CharField(blank=True, max_length=30, null=True)),
                ('avans', models.IntegerField()),
                ('odpoved', models.IntegerField()),
                ('stOdr', models.IntegerField()),
                ('stOtr', models.IntegerField()),
                ('tip', models.CharField(blank=True, max_length=30, null=True)),
                ('stSob', models.IntegerField()),
                ('cena', models.IntegerField()),
            ],
        ),
    ]
