# Generated by Django 4.1.5 on 2023-03-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0006_ponudba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponudba',
            name='stOtr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
