# Generated by Django 4.1.5 on 2023-03-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0010_remove_ponudba_stsob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ponudba',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='ponudba',
            name='zahteve',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vnosgostov',
            name='IDponudbe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='ponudba',
            index=models.Index(fields=['-id'], name='Rezervacije_id_42ed31_idx'),
        ),
    ]
