# Generated by Django 4.1.5 on 2023-03-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0012_ponudba_datumvnosa_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponudba',
            name='do_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ponudba',
            name='od_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
