# Generated by Django 4.1.5 on 2023-03-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0014_vnosgostov_datumvnosa_dt_vnosgostov_do_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnosgostov',
            name='status_rez',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
