# Generated by Django 4.1.5 on 2023-04-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0015_vnosgostov_status_rez'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=255, verbose_name='Opis')),
                ('cena', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cena')),
                ('kolicina', models.IntegerField(verbose_name='Količina')),
                ('enota', models.CharField(max_length=10)),
                ('ddv', models.CharField(max_length=20)),
                ('bruto_z_ddv', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bruto cena z ddv')),
                ('bruto_suma_z_ddv', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bruto cena z ddv')),
            ],
        ),
    ]
