# Generated by Django 4.1.5 on 2023-04-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0016_bar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bar',
            new_name='Bar_cenik',
        ),
    ]
