# Generated by Django 4.1.5 on 2023-04-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0017_rename_bar_bar_cenik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar_narocila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdaj', models.DateTimeField(auto_now_add=True)),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rezervacije.bar_cenik')),
                ('gost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rezervacije.vnosgostov')),
            ],
        ),
    ]
