# Generated by Django 4.1.5 on 2023-04-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0021_remove_vnosgostov_noc_sk_vnosgostov_cena_nocitve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnosgostov',
            name='cena_nocitve',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cena nočitve'),
        ),
    ]
