# Generated by Django 4.1.5 on 2023-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0022_alter_vnosgostov_cena_nocitve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnosgostov',
            name='nocitev_skupaj',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nočitev skupaj'),
        ),
    ]
