# Generated by Django 4.1.5 on 2023-04-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0023_alter_vnosgostov_nocitev_skupaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnosgostov',
            name='st_noci',
            field=models.IntegerField(blank=True, null=True, verbose_name='Noči skupaj'),
        ),
    ]
