# Generated by Django 4.1.5 on 2023-04-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0024_vnosgostov_st_noci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar_cenik',
            name='ddv',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='DDV'),
        ),
    ]
