# Generated by Django 4.1.5 on 2023-04-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0025_alter_bar_cenik_ddv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnosgostov',
            name='StanjeTTAX',
            field=models.CharField(max_length=100),
        ),
    ]
