# Generated by Django 4.1.5 on 2023-04-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0026_alter_vnosgostov_stanjettax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnosgostov',
            name='AvansEUR',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
