# Generated by Django 4.1.5 on 2023-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0027_alter_vnosgostov_avanseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnosgostov',
            name='datum_odpovedi_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vnosgostov',
            name='AvansEUR',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
