# Generated by Django 4.1.5 on 2023-06-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezervacije', '0031_alter_vnosgostov_rokplacilaavansa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnosgostov',
            name='status_placila',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
