# Generated by Django 4.1.5 on 2023-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Akcija', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChListSobaID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opis', models.CharField(max_length=20)),
                ('SobaID', models.CharField(max_length=30)),
                ('StSobe', models.IntegerField()),
                ('VseOK', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Graf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S0', models.CharField(max_length=20, null=True)),
                ('S1', models.CharField(max_length=20, null=True)),
                ('S2', models.CharField(max_length=20, null=True)),
                ('S3', models.CharField(max_length=20, null=True)),
                ('S4', models.CharField(max_length=20, null=True)),
                ('S5', models.CharField(max_length=20, null=True)),
                ('S6', models.CharField(max_length=20, null=True)),
                ('S7', models.CharField(max_length=20, null=True)),
                ('S8', models.CharField(max_length=20, null=True)),
                ('S9', models.CharField(max_length=20, null=True)),
                ('S10', models.CharField(max_length=20, null=True)),
                ('S11', models.CharField(max_length=20, null=True)),
                ('S12', models.CharField(max_length=20, null=True)),
                ('S13', models.CharField(max_length=20, null=True)),
                ('S14', models.CharField(max_length=20, null=True)),
                ('S15', models.CharField(max_length=20, null=True)),
                ('S16', models.CharField(max_length=20, null=True)),
                ('S17', models.CharField(max_length=20, null=True)),
                ('S18', models.CharField(max_length=20, null=True)),
                ('S19', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObravnavaniDatum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naziv', models.CharField(max_length=25)),
                ('DatumObravnavani', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pospravljanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Soba', models.IntegerField(choices=[(10, 10), (20, 20)], default='10')),
                ('Akcija', models.CharField(max_length=20)),
                ('Za_Oseb', models.IntegerField()),
                ('Status', models.CharField(max_length=20)),
                ('DatumVnosa', models.CharField(max_length=20)),
                ('Ime', models.CharField(max_length=25)),
                ('Agencija', models.CharField(choices=[('', ''), ('BookingCom', 'BookingCom'), ('Siteminder', 'Siteminder')], default='', max_length=20)),
                ('Od', models.CharField(max_length=20)),
                ('Do', models.CharField(max_length=20)),
                ('Cena', models.CharField(max_length=20)),
                ('Oseb', models.CharField(max_length=20)),
                ('Tip', models.CharField(max_length=20)),
                ('Drzava', models.CharField(max_length=255)),
                ('Zahteve', models.CharField(max_length=254, null=True)),
                ('Alergije', models.CharField(max_length=25)),
                ('RNA', models.CharField(max_length=20)),
                ('StatusZajtrk', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PospravljanjePrihodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Soba', models.IntegerField()),
                ('St_Oseb', models.IntegerField()),
                ('Status', models.CharField(max_length=20)),
                ('StatusCheckIn', models.CharField(max_length=20, null=True)),
                ('DatumVnosa', models.CharField(max_length=20)),
                ('Ime', models.CharField(max_length=25)),
                ('Agencija', models.CharField(max_length=20)),
                ('Od', models.CharField(max_length=20)),
                ('Do', models.CharField(max_length=20)),
                ('Cena', models.CharField(max_length=20)),
                ('Tip', models.CharField(max_length=20)),
                ('Drzava', models.CharField(max_length=255)),
                ('Zahteve', models.CharField(max_length=254, null=True)),
                ('Alergije', models.CharField(max_length=25)),
                ('RNA', models.CharField(max_length=20)),
                ('Ttax', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrazneSobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Soba', models.IntegerField()),
                ('NaslPrh', models.CharField(max_length=20)),
                ('DniDoPrih', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VnosGostov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumvnosa', models.DateField(auto_now_add=True)),
                ('sifravnosa', models.CharField(max_length=100, null=True, verbose_name='Šifra vnosa')),
                ('imestranke', models.CharField(max_length=100, verbose_name='Ime Stranke')),
                ('agencija', models.CharField(max_length=100, verbose_name='Agencija')),
                ('od', models.DateField(verbose_name='Datum OD')),
                ('do', models.DateField(verbose_name='Datum DO')),
                ('dniPredr', models.IntegerField(blank=True, null=True)),
                ('CENA', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('stsobe', models.IntegerField()),
                ('SO', models.IntegerField()),
                ('tip', models.CharField(max_length=100)),
                ('RNA', models.CharField(max_length=100)),
                ('AvansEUR', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('DR', models.CharField(max_length=100)),
                ('zahteve', models.TextField(blank=True, null=True)),
                ('Alergije', models.CharField(blank=True, max_length=100, null=True)),
                ('Mes_Let', models.CharField(blank=True, max_length=100, null=True)),
                ('Noc_SK', models.IntegerField(blank=True, null=True)),
                ('StanjeTTAX', models.CharField(max_length=100)),
                ('OdpRok', models.IntegerField(blank=True, null=True)),
                ('IDponudbe', models.IntegerField(blank=True, null=True)),
                ('RokPlacilaAvansa', models.DateField(blank=True, null=True)),
                ('Zaklenjena', models.CharField(blank=True, max_length=100, null=True)),
                ('OdpovedDne', models.DateField(blank=True, null=True)),
                ('SOTR', models.IntegerField(blank=True, null=True)),
                ('SOMAL', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
