# Generated by Django 4.1.5 on 2023-01-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0003_alter_vnosgostov_stanjettax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnosgostov',
            name='datumvnosa',
            field=models.CharField(max_length=30),
        ),
    ]
