# Generated by Django 4.1.5 on 2023-01-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0004_alter_vnosgostov_datumvnosa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnosgostov',
            name='datumvnosa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
