# Generated by Django 4.1.5 on 2023-05-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0009_pospravljanjeprihodi_cas_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pospravljanje',
            name='cas_ciscenja',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pospravljanje',
            name='cas_zajtrka',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pospravljanje',
            name='status_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pospravljanje',
            name='status_zajtrk_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pospravljanje',
            name='uni_koda',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pospravljanjeprihodi',
            name='uni_koda',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
