# Generated by Django 4.1.5 on 2023-05-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0010_pospravljanje_cas_ciscenja_pospravljanje_cas_zajtrka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pospravljanje',
            name='ok1',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pospravljanje',
            name='ok2',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pospravljanje',
            name='ok3',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pospravljanje',
            name='ok4',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
