# Generated by Django 4.1.5 on 2023-06-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0011_pospravljanje_ok1_pospravljanje_ok2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graf',
            name='S20',
        ),
        migrations.RemoveField(
            model_name='graf',
            name='S21',
        ),
        migrations.RemoveField(
            model_name='graf',
            name='S22',
        ),
        migrations.RemoveField(
            model_name='graf',
            name='S23',
        ),
        migrations.RemoveField(
            model_name='graf',
            name='S24',
        ),
        migrations.RemoveField(
            model_name='graf',
            name='S25',
        ),
        migrations.RemoveField(
            model_name='graf',
            name='S26',
        ),
        migrations.RemoveField(
            model_name='graf',
            name='S27',
        ),
        migrations.RemoveField(
            model_name='graf',
            name='S28',
        ),
        migrations.RemoveField(
            model_name='pospravljanjeprihodi',
            name='ok1',
        ),
        migrations.RemoveField(
            model_name='pospravljanjeprihodi',
            name='ok2',
        ),
        migrations.RemoveField(
            model_name='pospravljanjeprihodi',
            name='ok3',
        ),
        migrations.RemoveField(
            model_name='pospravljanjeprihodi',
            name='ok4',
        ),
    ]
