# Generated by Django 4.1.5 on 2023-06-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0012_remove_graf_s20_remove_graf_s21_remove_graf_s22_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graf',
            name='S20',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graf',
            name='S21',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graf',
            name='S22',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graf',
            name='S23',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graf',
            name='S24',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graf',
            name='S25',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graf',
            name='S26',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graf',
            name='S27',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graf',
            name='S28',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
